/** @format */

export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_ALL_PROFILES = "GET_ALL_PROFILES";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST"
export const chatConstants = {
    CHANGE_ROOM: "CHANGE_ROOM",
    INIT_MESSAGE_ARRAY: "INIT_MESSAGE_ARRAY",
    NEW_MESSAGE: "NEW_MESSAGE",
    READ_MESSAGES: "READ_MESSAGES",
    RECEIVE_READ_MESSAGES: "RECEIVE_READ_MESSAGES",
    CHANGE_ACTIVITY_STATUS: "CHANGE_ACTIVITY_STATUS",
    ADD_NEW_ROOM: "ADD_NEW_ROOM",
    INC_MESSAGE_COUNT: "INC_MESSAGE_COUNT",
    SEARCH_USERS: "SEARCH_USERS",
  
    OPEN_CALLING_MODAL: "OPEN_CALLING_MODAL",
    CLOSE_CALLING_MODAL: "CLOSE_CALLING_MODAL",
  
    NEW_ANSWER: "NEW_ANSWER",
  
    OPEN_ANSWERING_MODAL: "OPEN_ANSWERING_MODAL",
    CLOSE_ANSWERING_MODAL: "CLOSE_ANSWERING_MODAL",
  
    TYPING: "TYPING",
    STOPPED_TYPING: "STOPPED_TYPING",
  
    GET_ROOMS_REQUEST: "GET_ROOMS_REQUEST",
    GET_ROOMS_SUCCESS: "GET_ROOMS_SUCCESS",
  
    GET_MESSAGES_INITIAL_REQUEST: "GET_MESSAGES_INITIAL_REQUEST",
    GET_MESSAGES_REQUEST: "GET_MESSAGES_REQUEST",
    GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
  
    SEND_MESSAGE_REQUEST: "SEND_MESSAGE_REQUEST",
    SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  
    NEW_IMAGE_MESSAGE_REQUEST: "NEW_IMAGE_MESSAGE_REQUEST",
    NEW_IMAGE_MESSAGE_SUCCESS: "NEW_IMAGE_MESSAGE_SUCCESS"
  };
  
